---
name: mediawiki-graph
abstract: Integrate Graph::Easy into Wikimedia
version: 0.19
version_from: graphcnv
license: gpl
distribution_type: module
generated_by: mediawiki-graph version 0.19
installdirs: site
requires:
  Config::Tiny: 2.02
  Digest::SHA1: 2.1
  Graph::Easy: 0.44
